# Copyright (c) 2023 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: 0BSD

version: 2.1

jobs:
  make:
    docker:
    - image: cimg/python:3.9.18
    steps:
      - checkout
      - run:
         name: make
         command: |
           set -euo pipefail

           make -C python all

workflows:
  version: 2
  build:
    jobs:
    - make
